#!/usr/bin/env ruby
# frozen_string_literal: true

require "rubygems"
require "bundler/setup"
require "appraisal"
require "appraisal/cli"

begin
  Appraisal::CLI.start
rescue Appraisal::AppraisalsNotFound => e
  puts e.message
  exit 127
end
